In [1]:
#Libraries
import pandas as pd

In [2]:
#Load data
df = pd.read_csv("C:\ARCHIVOS\DOCUMENTS\Alvaro Universidad\M2 FIT\Practice\Sample - Superstore.csv",encoding = 'latin1')

<>:2: SyntaxWarning: invalid escape sequence '\A'
<>:2: SyntaxWarning: invalid escape sequence '\A'
C:\Users\maryl\AppData\Local\Temp\ipykernel_7012\1173986111.py:2: SyntaxWarning: invalid escape sequence '\A'
  df = pd.read_csv("C:\ARCHIVOS\DOCUMENTS\Alvaro Universidad\M2 FIT\Practice\Sample - Superstore.csv",encoding = 'latin1')

In [10]:
#Exercise 1: Total Sales per Category
result = df.groupby('Category')['Sales'].sum().round(2)
print(f"Total Sales per Category \n{result}")

Total Sales per Category
Category
Furniture          741999.80
Office Supplies    719047.03
Technology         836154.03
Name: Sales, dtype: float64

In [18]:
#Exercise 2: Multiple KPIs with Aggregate Functions
result2 = df.groupby('Category').agg(
    Total_Sales = ('Sales', 'sum'),
    Average_Sales = ('Sales', 'mean'),
    Total_Transactions = ('Sales','count'),
    Total_Profit = ('Profit','sum')
).round(2)
result2['Margin pct'] = round(result2['Total_Profit']/result2['Total_Sales']*100,2)
result2.sort_values('Total_Sales', ascending=False)

,Total_Sales,Average_Sales,Total_Transactions,Total_Profit,Margin pct
Category,,,,,
Technology,836154.03,452.71,1847,145454.95,17.40
Furniture,741999.80,349.83,2121,18451.27,2.49
Office Supplies,719047.03,119.32,6026,122490.80,17.04

In [19]:
#Exercise 3: Group by 2 columns + pivot table 
#Group by 2 columns
by_region_cat = df.groupby(['Region','Category'])['Sales'].sum().reset_index()
#Pivot Table
table = df.pivot_table(values='Sales', index='Region',columns='Category', aggfunc='sum')
round(table,0)

Category  Furniture  Office Supplies  Technology
Region
Central    163797.0         167026.0    170416.0
East       208291.0         205516.0    264974.0
South      117299.0         125651.0    148772.0
West       252613.0         220853.0    251992.0