**Week 7: Rankings**

In [1]:
#Libraries
import pandas as pd

In [2]:
#Load data
df = pd.read_csv("C:\ARCHIVOS\DOCUMENTS\Alvaro Universidad\M2 FIT\Practice\Sample - Superstore.csv",encoding = 'latin1')

<>:2: SyntaxWarning: invalid escape sequence '\A'
<>:2: SyntaxWarning: invalid escape sequence '\A'
C:\Users\maryl\AppData\Local\Temp\ipykernel_23656\1173986111.py:2: SyntaxWarning: invalid escape sequence '\A'
  df = pd.read_csv("C:\ARCHIVOS\DOCUMENTS\Alvaro Universidad\M2 FIT\Practice\Sample - Superstore.csv",encoding = 'latin1')

**Exercise 1: Top N Products**

In [7]:
top5 = (df.groupby('Product Name')['Sales']
        .sum()
        .sort_values(ascending=True)
        .head(5)
        .reset_index())
top5.columns = ['Products','Total Sales']
display(top5)

                                            Products  Total Sales
0  Eureka Disposable Bags for Sanitaire Vibra Gro...        1.624
1                                            Avery 5        5.760
2                                           Xerox 20        6.480
3                                Grip Seal Envelopes        7.072
4  Avery Hi-Liter Pen Style Six-Color Fluorescent...        7.700

**Exercise 2: Rank Customers within each region**

In [6]:
by_cust = df.groupby(['Region','Customer Name'])['Sales'].sum().reset_index()
by_cust['rank'] = (by_cust.groupby(['Region'])['Sales']
                   .rank(ascending=False, method='dense'))
#Top 3 per Region
top3 = by_cust[by_cust['rank']<=3].sort_values(['Region','rank'])
display(top3)

       Region   Customer Name      Sales  rank
579   Central    Tamara Chand  18437.138   1.0
5     Central   Adrian Barton  12181.594   2.0
57    Central    Becky Martin  10539.896   3.0
1276     East    Tom Ashbrook  13723.498   1.0
916      East    Hunter Lopez  10522.550   2.0
705      East    Bill Shonely  10022.293   3.0
1745    South     Sean Miller  23669.196   1.0
1736    South    Sanjit Engle   8805.040   2.0
1499    South  Grant Thornton   8167.420   3.0
2354     West    Raymond Buch  14345.276   1.0
2199     West    Ken Lonsdale   8472.394   2.0
2029     West    Edward Hooks   7447.770   3.0

**Exercise 3: Month over month change and Running Total**

In [9]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

monthly = df.set_index('Order Date')['Sales'].resample('ME').sum().reset_index()
monthly.columns =['Month','Sales']

monthly['Prev. Month'] = monthly['Sales'].shift(1)
monthly['Mom Pct'] = monthly['Sales'].pct_change()*100
monthly['Running Total'] = monthly['Sales'].cumsum()

monthly.tail(10)

        Month        Sales  Prev. Month     Mom Pct  Running Total
38 2017-03-31   58872.3528   20301.1334  189.995399   1.687130e+06
39 2017-04-30   36521.5361   58872.3528  -37.964878   1.723652e+06
40 2017-05-31   44261.1102   36521.5361   21.191809   1.767913e+06
41 2017-06-30   52981.7257   44261.1102   19.702659   1.820895e+06
42 2017-07-31   45264.4160   52981.7257  -14.565984   1.866159e+06
43 2017-08-31   63120.8880   45264.4160   39.449249   1.929280e+06
44 2017-09-30   87866.6520   63120.8880   39.203764   2.017147e+06
45 2017-10-31   77776.9232   87866.6520  -11.483001   2.094924e+06
46 2017-11-30  118447.8250   77776.9232   52.291734   2.213372e+06
47 2017-12-31   83829.3188  118447.8250  -29.226798   2.297201e+06