**Week 04: Joins**

In [2]:
#Libraries
import pandas as pd
#Load data
df = pd.read_csv("C:\ARCHIVOS\DOCUMENTS\Alvaro Universidad\M2 FIT\Practice\Sample - Superstore.csv",encoding = 'latin1')

<>:4: SyntaxWarning: invalid escape sequence '\A'
<>:4: SyntaxWarning: invalid escape sequence '\A'
C:\Users\maryl\AppData\Local\Temp\ipykernel_16656\2291493658.py:4: SyntaxWarning: invalid escape sequence '\A'
  df = pd.read_csv("C:\ARCHIVOS\DOCUMENTS\Alvaro Universidad\M2 FIT\Practice\Sample - Superstore.csv",encoding = 'latin1')

In [4]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [7]:
#Exercise 0: Prepare 2 datasets 
#Dataset 1
orders = df[['Order ID','Order Date','Customer ID','Region','Segment']].drop_duplicates()
#Dataset 2
line_items = df[['Order ID','Product Name','Category','Sales','Profit']]
print(f'Orders: {orders.shape} | Line items: {line_items.shape}')

Orders: (5009, 5) | Line items: (9994, 5)

In [8]:
#Exercise 1: Join 2 tables
combined = pd.merge(orders,line_items, on = 'Order ID', how = 'inner')
print(f'Result: {combined.shape}')

Result: (9994, 9)

In [9]:
#Exercise 2: Use of Agg functions
result = combined.groupby('Segment').agg(
    num_orders = ('Order ID','nunique'),
    total_sales = ('Sales','sum'),
    avg_ticket = ('Sales','mean')
).round(2).sort_values('total_sales', ascending=False)
result

             num_orders  total_sales  avg_ticket
Segment
Consumer           2586   1161401.34      223.73
Corporate          1514    706146.37      233.82
Home Office         909    429653.15      240.97

In [13]:
#Exercise 3: Find unmatched rows

#Add fake data
fake = pd.DataFrame({'Order ID': ['CA-FAKE-001'], 'Order Date':['2017-06-15'],'Customer ID':['CUST-999'],'Region':['West'],'Segment':['Consumer']})
orders_extra = pd.concat([orders,fake],ignore_index = True)

#Left Join
left = pd.merge(orders_extra,line_items, on='Order ID', how='left')
unmatched = left[left['Sales'].isna()]
unmatched

,Order ID,Order Date,Customer ID,Region,Segment,Product Name,Category,Sales,Profit
9994,CA-FAKE-001,2017-06-15,CUST-999,West,Consumer,NaN,NaN,NaN,NaN